name: Security Scan
on: [push]
jobs:
  checkov-job:
    runs-on: ubuntu-latest
    name: checkov-action
    steps:
      - name: Checkout repo
        uses: actions/checkout@master
        
      - name: Run Checkov action
        id: checkov
        uses: bridgecrewio/checkov-action@master
        with:
          directory: .
          skip_check: CKV* 
          quiet: true 
          soft_fail: true 
          framework: terraform 
          output_format: json 
          output_file_path: reports
          log_level: WARN 
